name: Sync to Hugging Face Space
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # <-- Chìa khóa đây: Chỉ tải code hiện tại, vứt bỏ toàn bộ lịch sử cũ
          lfs: false
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Ép in file README.md chuẩn
          echo "---" > README.md
          echo "title: Paper Search API" >> README.md
          echo "emoji: 🚀" >> README.md
          echo "colorFrom: blue" >> README.md
          echo "colorTo: green" >> README.md
          echo "sdk: docker" >> README.md
          echo "pinned: false" >> README.md
          echo "---" >> README.md
          
          # 2. Xóa lịch sử cũ và tạo mới
          rm -rf .git
          git init
          git branch -M main
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 3. CHIÊU CUỐI: ÉP GIT PHẢI LẤY FILE NÀY (Bất chấp .gitignore)
          git add -f README.md
          git add .
          
          # 4. Đóng gói và đẩy đi
          git commit -m "Force deploy with strict README"
          
          # Nhớ thay lại link thật của bạn ở dòng dưới nha
          git push --force https://nguyenhoangynhi:${HF_TOKEN}@huggingface.co/spaces/nguyenhoangynhi/paper-search-api main
